# Generated by Django 3.2.16 on 2023-02-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_alter_about_about_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description6',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description7',
            field=models.TextField(null=True),
        ),
    ]
